Name                = "veronica"
Environment         = "development"

# global defines
[global]
MaxProcs            = 1 
MaxChannelSize      = 10240
MonitorInterval     = 30        # monitor interval, unit: second

PprofMode           = true
PprofAddr           = "0.0.0.0:2234"

[demo]
Test                = "demo"
Threads             = 3

[tickers]
    [tickers.demoDoing]
    Interval        = 10

# databases
[databases]         # database connection config
    [databases.demo]
    Host            = "127.0.0.1"
    Port            = 3306
    User            = "root"
    Password        = "demo"
    DbName          = "demo"
    LogMode         = true
    [databases.demo2]
    Host            = "127.0.0.2"
    Port            = 3306
    User            = "root"
    Password        = "demo2"
    DbName          = "demo2"
    LogMode         = false

# logger config, more details please see seelog
[logger]            # default, monitor must have
    [logger.default]
    conf            = """
    <seelog type="sync" minlevel="debug">
        <outputs formatid="main">
            <console/>
            <rollingfile type="size" filename="logs/main.log" maxsize="1024000000" maxrolls="10"/>
            <filter levels="error">
                 <file path="logs/main.err.log"/>
            </filter>
        </outputs>
        <formats>
            <format id="main" format="[%Date %Time] [%LEVEL] [%Func: %Line] %Msg%n"/>
        </formats>
    </seelog>
    """
    [logger.monitor]
    conf            = """
    <seelog type="sync" minlevel="debug">
        <outputs formatid="main">
            <console/>
            <rollingfile type="size" filename="logs/monitor.log" maxsize="102400000" maxrolls="5"/>
        </outputs>
        <formats>
            <format id="main" format="[%Date %Time] [%LEVEL] %Msg%n"/>
        </formats>
    </seelog>
    """
    [logger.demo]
    conf            = """
    <seelog type="sync" minlevel="debug">
        <outputs formatid="main">
            <console/>
            <rollingfile type="size" filename="logs/demo.log" maxsize="1024000000" maxrolls="10"/>
        </outputs>
        <formats>
            <format id="main" format="[%Date %Time] [%LEVEL] [%Func: %Line] %Msg%n"/>
        </formats>
    </seelog>
    """
